tuple1 = ("Git", "HTML", "Python")
print(type(tuple1))
tupl2 = ("Java", "Spring", "Selenium", 1, 2, 4)
print(tupl2)
tuplis1 = ("Data Science", "Machine Learning", [10, 20, 30])
print(tuplis1)
nestuple1 = ("Power Bi", "RPA", "SEEK", ("DO", "DI", "ML"))
print(nestuple1)
mytuple = ("Red", "Green", "Yellow", "Pink", "Black", "Orange")
print(mytuple[1])
print(mytuple[-2])
print(mytuple[3:5])
print(mytuple[-3:-1])
tuplis1[2][0] = 12.4
print(tuplis1)
del tuple1
mytup2 = ('Daniel', 'Sarah', 'Bosch',
          'Lindon', 'Brevis', 'Archer', 'Smith')
print("count values:", mytup2.count('Lindon'))
print("Index values:", mytup2.index('Bosch'))
